name: Release Maven



on:
  push:
    tags:
      - '*'
# on: [push]



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          distribution: "Liberica"
          java-version: 1.8
          java-package: jdk+fx
      - name: Build with Maven
        run:
          mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V 
      - name: Create Release
        id: create_release
        uses: SummerSec/create-release@master
        with:
          tag_name: ${{ github.ref }}
          release-name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE }}


      - name: Upload a Build Artifact
        id: upload-build-artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          # Artifact name
          name: # optional, default is artifact
            SPATool-${{steps.create_release.outputs.tag}}-SNAPSHOT-all.jar
          # A file, directory or wildcard pattern that describes what to upload
          path:
            target/*-SNAPSHOT-all.jar
          # The desired behavior if no files are found using the provided path.

      - name: Auto Upload Release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE}}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/work/SpringBootExploit/SpringBootExploit/target/SpringBootExploit-${{ steps.create_release.outputs.tag }}-SNAPSHOT-all.jar
          asset_name: SpringBootExploit-${{ steps.create_release.outputs.tag }}-SNAPSHOT-all.jar
          asset_content_type: application/java-archive
